// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpzqkuyzpijsjzumivkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwenFrdXl6cGlqc2p6dW1pdmtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTIyMDIsImV4cCI6MjA1OTk4ODIwMn0.dNxumRlYv7QNB8WKny5K4WQPYIOz0SkTnmB705o8VtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);